version: "3.8"

services:
  # Servicio de PostgreSQL
  postgres:
    image: postgres:16
    container_name: acadeval_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AcadEvalDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - acadeval_network

  # Servicio opcional de pgAdmin para gestionar PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: acadeval_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@acadeval.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - acadeval_network

networks:
  acadeval_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
