name: "Mejora de Documentación"
description: "Solicitar una mejora o corrección en la documentación"
title: "[Documentación]: "
labels: ["documentation"]

body:
  - type: markdown
    attributes:
      value: "# Descripción de la Mejora\n\nDescribe la mejora o corrección que propones para la documentación."

  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: "Explica qué parte de la documentación debe mejorarse o corregirse."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Contexto Adicional\nProporciona cualquier información adicional que pueda ayudar a mejorar la documentación."

  - type: textarea
    id: additional-context
    attributes:
      label: Contexto Adicional
      description: "Agrega cualquier información relevante que deba ser considerada."
    validations:
      required: false
