name: "Mejora de Documentación"
description: "Propuesta de mejora en la documentación"
title: "📄 [Docs]: "
labels: ["documentation"]

body:
  - type: markdown
    attributes:
      value: "# 📖 Descripción\n\nDescribe la mejora en la documentación."

  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: "Explica los cambios sugeridos y su beneficio."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🎨 Tipo de Cambio"

  - type: checkboxes
    id: type-of-change
    attributes:
      label: Tipo de Cambio
      options:
        - label: "➕ Agregar información faltante"
        - label: "✏️ Corregir errores existentes"
        - label: "🔄 Reestructurar el contenido"
        - label: "🛠 Otro (especificar en la descripción)"

  - type: markdown
    attributes:
      value: "## 📃 Recursos Adicionales"

  - type: textarea
    id: additional-resources
    attributes:
      label: Recursos Adicionales
      description: "Adjunta enlaces o material relevante."
    validations:
      required: false
