@host = https://localhost:7004

GET {{host}}/api/identity/login/
Accept: application/json

###

POST {{host}}/api/identity/login/
Accept: application/json
Content-Type: application/json

{
    "email": "tbanchioalumno@itec-elmolino.edu.ar",
    "password": "Tomasbanchio16_"
}
