name: CD - Deploy AcadEvalSys to Azure (Development)

on:
  push:
    branches:
      - development
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: acaditec
  AZURE_WEBAPP_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP_DEV }}
  AZURE_CONTAINER_REGISTRY_LOGIN_SERVER: acadevalitecregistry.azurecr.io
  IMAGE_NAME: acadevalsystem
  DOCKERFILE_PATH: ./src/AcadEvalSys.WEB/AcadEvalSys.WEB.Server/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Development

    steps:
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_WEBAPP_RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ env.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --docker-registry-server-url https://${{ env.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}

      - name: Restart Azure Web App
        run: |
          az webapp restart \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_WEBAPP_RESOURCE_GROUP }}
