name: Test Workflow

on:
  push:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello, GitHub Actions! This is a test."
